/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
    "../external_ui/src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Brand colors from external_ui
        "brand-primary": "#442a22",
        "brand-brown": "#5d4037",
        "brand-secondary": "#655d5a",
        "brand-bg": "#f9f9f9",
        "brand-sand": "#ece0dc",
        "brand-dark": "#1a1c1c",
        "brand-stone": "#827470",
        "brand-moss": "#8d9b91",
        "brand-ivory": "#f5f5f5",

        // Design system colors
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#504441",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#827470",
        "outline-variant": "#d4c3be",
        "surface-tint": "#77574d",
        "primary": "#442a22",
        "on-primary": "#ffffff",
        "primary-container": "#5d4037",
        "on-primary-container": "#d4ada1",
        "inverse-primary": "#e7bdb1",
        "secondary": "#655d5a",
        "on-secondary": "#ffffff",
        "secondary-container": "#ece0dc",
        "on-secondary-container": "#6b6360",
        "tertiary": "#21333a",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#384a51",
        "on-tertiary-container": "#a5b9c1",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#e7bdb1",
        "on-primary-fixed": "#2c160e",
        "on-primary-fixed-variant": "#5d4037",
        "secondary-fixed": "#ece0dc",
        "secondary-fixed-dim": "#cfc4c0",
        "on-secondary-fixed": "#201a18",
        "on-secondary-fixed-variant": "#4c4542",
        "tertiary-fixed": "#d2e6ef",
        "tertiary-fixed-dim": "#b6cad2",
        "on-tertiary-fixed": "#0b1e24",
        "on-tertiary-fixed-variant": "#374951",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "primary": "#442a22",
        "secondary": "#655d5a",
        "tertiary": "#21333a",
        neutral: {
          50:  "#fafaf8",
          100: "#f4f3ef",
          200: "#e9e7e0",
          300: "#d8d5ca",
          400: "#c0bbb0",
          500: "#a39e94",
          600: "#857f74",
          700: "#6c6760",
          800: "#5a564f",
          900: "#4c4841",
          950: "#29271f",
        },
        // Shadcn UI variables
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      fontFamily: {
        sans: ["Montserrat", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["Playfair Display", "ui-serif", "Georgia", "serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "caption": ["Montserrat", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.875rem" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.8", "fontWeight": "400" }],
      },
      spacing: {
        "margin-desktop": "64px",
        "section-gap": "120px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "24px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "0.125rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          from: { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(8px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-out",
        shimmer: "shimmer 2s linear infinite",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-out-right": "slide-out-right 0.3s ease-out",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
      boxShadow: {
        "card": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "card-hover": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
