"""add_charity_models

Revision ID: 1fa04f2c4cf7
Revises: ce541a6b2a31
Create Date: 2026-06-16 22:07:10.107036
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1fa04f2c4cf7'
down_revision: Union[str, None] = 'ce541a6b2a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('raised_amount', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charity_campaigns_id'), 'charity_campaigns', ['id'], unique=False)
    op.create_table('charity_transactions',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('donor_recipient', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['charity_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charity_transactions_id'), 'charity_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charity_transactions_id'), table_name='charity_transactions')
    op.drop_table('charity_transactions')
    op.drop_index(op.f('ix_charity_campaigns_id'), table_name='charity_campaigns')
    op.drop_table('charity_campaigns')
    # ### end Alembic commands ###
