"""add reply to reviews

Revision ID: 31113e52a49f
Revises: 4de6d6f39b6e
Create Date: 2026-06-13 18:21:50.106788
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '31113e52a49f'
down_revision: Union[str, None] = '4de6d6f39b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reply')
    # ### end Alembic commands ###
