"""add image_url to chat_messages

Revision ID: 3c5be048be14
Revises: 966a35e81117
Create Date: 2026-06-13 12:53:32.353781
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3c5be048be14'
down_revision: Union[str, None] = '966a35e81117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'image_url')
    # ### end Alembic commands ###
