"""add is_anonymous to reviews

Revision ID: 4de6d6f39b6e
Revises: c39aa7a33dfd
Create Date: 2026-06-13 18:18:03.508648
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4de6d6f39b6e'
down_revision: Union[str, None] = 'c39aa7a33dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_anonymous')
    # ### end Alembic commands ###
