"""create missing tables

Revision ID: 537acfece583
Revises: a6c085a2bc81
Create Date: 2026-07-01 15:36:50.276337
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '537acfece583'
down_revision: Union[str, None] = 'a6c085a2bc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('percentage', 'fixed', 'free_shipping', name='promotiontype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_order', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('applicable_products', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', name='promotionstatus'), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('target_customer_tier', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('stock_vouchers',
    sa.Column('voucher_code', sa.String(length=100), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('delivery_status', sa.String(length=100), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_duration_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_code')
    )
    op.create_index(op.f('ix_stock_vouchers_id'), 'stock_vouchers', ['id'], unique=False)
    op.create_table('traffic_channels',
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_channels_channel_name'), 'traffic_channels', ['channel_name'], unique=True)
    op.create_index(op.f('ix_traffic_channels_id'), 'traffic_channels', ['id'], unique=False)
    op.create_table('audit_vouchers',
    sa.Column('voucher_code', sa.String(length=100), nullable=False),
    sa.Column('auditor', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_discrepancy', sa.Integer(), nullable=False),
    sa.Column('stock_voucher_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_voucher_id'], ['stock_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_code')
    )
    op.create_index(op.f('ix_audit_vouchers_id'), 'audit_vouchers', ['id'], unique=False)
    op.create_table('audit_voucher_items',
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('system_stock', sa.Integer(), nullable=False),
    sa.Column('actual_stock', sa.Integer(), nullable=False),
    sa.Column('discrepancy', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['audit_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_voucher_items_id'), 'audit_voucher_items', ['id'], unique=False)
    op.create_table('stock_voucher_items',
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['stock_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_voucher_items_id'), 'stock_voucher_items', ['id'], unique=False)
    op.add_column('charity_campaigns', sa.Column('slogan', sa.String(length=255), nullable=True))
    op.add_column('charity_campaigns', sa.Column('gallery_images', sa.Text(), nullable=True))
    op.add_column('charity_campaigns', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('charity_campaigns', sa.Column('quote', sa.String(length=500), nullable=True))
    op.add_column('charity_campaigns', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('charity_transactions', sa.Column('order_code', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost_price')
    op.drop_column('charity_transactions', 'order_code')
    op.drop_column('charity_campaigns', 'address')
    op.drop_column('charity_campaigns', 'quote')
    op.drop_column('charity_campaigns', 'content')
    op.drop_column('charity_campaigns', 'gallery_images')
    op.drop_column('charity_campaigns', 'slogan')
    op.drop_index(op.f('ix_stock_voucher_items_id'), table_name='stock_voucher_items')
    op.drop_table('stock_voucher_items')
    op.drop_index(op.f('ix_audit_voucher_items_id'), table_name='audit_voucher_items')
    op.drop_table('audit_voucher_items')
    op.drop_index(op.f('ix_audit_vouchers_id'), table_name='audit_vouchers')
    op.drop_table('audit_vouchers')
    op.drop_index(op.f('ix_traffic_channels_id'), table_name='traffic_channels')
    op.drop_index(op.f('ix_traffic_channels_channel_name'), table_name='traffic_channels')
    op.drop_table('traffic_channels')
    op.drop_index(op.f('ix_stock_vouchers_id'), table_name='stock_vouchers')
    op.drop_table('stock_vouchers')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
