"""add tier to customers

Revision ID: 972e044537ab
Revises: fcc9e2dee371
Create Date: 2026-06-10 10:43:04.931122
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '972e044537ab'
down_revision: Union[str, None] = 'fcc9e2dee371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('tier', sa.String(length=50), nullable=False, server_default='Tiêu chuẩn'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'tier')
    # ### end Alembic commands ###
