"""add settings model

Revision ID: a6c085a2bc81
Revises: fc4983879a75
Create Date: 2026-06-23 21:42:44.732617
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a6c085a2bc81'
down_revision: Union[str, None] = 'fc4983879a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('audit_vouchers_stock_voucher_id_fkey', 'audit_vouchers', type_='foreignkey')
    # op.create_foreign_key(None, 'audit_vouchers', 'stock_vouchers', ['stock_voucher_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_vouchers', type_='foreignkey')
    op.create_foreign_key('audit_vouchers_stock_voucher_id_fkey', 'audit_vouchers', 'stock_vouchers', ['stock_voucher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
