"""add_color_to_stock_voucher_items

Revision ID: b1647f7a4b37
Revises: 1fa04f2c4cf7
Create Date: 2026-06-21 13:43:06.399243
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b1647f7a4b37'
down_revision: Union[str, None] = '1fa04f2c4cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('stock_voucher_items', sa.Column('color', sa.String(length=100), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_voucher_items', 'color')
    # ### end Alembic commands ###
