"""create_traffic_channels

Revision ID: fc4983879a75
Revises: b1647f7a4b37
Create Date: 2026-06-21 14:00:27.098053
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fc4983879a75'
down_revision: Union[str, None] = 'b1647f7a4b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
